#%RAML 1.0
title: s-product-api
version: 1.0.0
baseUri: http://sspg.s-products-api.co.uk

securitySchemes:
  oauth_2: !include common-libraries/security-schemes/security-scheme-oauth-2.raml
  
  #securedBy: [ oauth_2 ]
traits:
  ExpectsContext: !include common-libraries/traits/trait-expects-context.raml
  ReturnsSuccess: !include common-libraries/traits/trait-returns-success.raml
  ReturnsNotFound:  !include common-libraries/traits/trait-returns-not-found.raml
  ReturnsNoContent: !include common-libraries/traits/trait-returns-no-content.raml
  ReturnsItemCreated: !include common-libraries/traits/trait-returns-item-created.raml
  NoCache: !include common-libraries/traits/trait-not-cacheable.raml
  Cacheable: !include common-libraries/traits/trait-cacheable.raml 
  CommonError: !include common-libraries/traits/trait-returns-common-errors.raml
  Pageable: !include common-libraries/traits/trait-pageable.raml

/products/{Id}:
  get:
    is: [ReturnsSuccess, ReturnsNotFound, ReturnsNoContent, NoCache, ExpectsContext,  Pageable,CommonError]
    displayName: get propery data
    responses:
      '200':
        description: OK
        body:
          application/json:
            example: !include examples/get-product-data-success-200.json